kind = "web"
previewPath = "/"
title = "Star Computer's Academy"
version = "1.0.0"
id = "artifacts/star-academy"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
localPort = 24973
name = "web"
paths = ["/"]

[services.development]
run = "pnpm --filter @workspace/star-academy run dev"

[services.env]
PORT = "24973"
BASE_PATH = "/"

[services.production]
build = ["pnpm", "--filter", "@workspace/star-academy", "run", "build"]
publicDir = "artifacts/star-academy/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"
